<?php

/**
 * @file
 * The Toolbar Edit Link module adds a Edit Node link to the toolbar.
 *
 * This module also check if the user have access administration page
 * and are on a node.
 */

/**
 * Implements hook_toolbar().
 */
function toolbar_edit_link_toolbar() {
  $node = \Drupal::routeMatch()->getParameter('node');

  if ((\Drupal::currentUser()->hasPermission('access administration pages')) && (!empty($node))) {
    $items = [];
    $nid = $node->id();
    $items['toolbar_edit_link'] = [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('Edit Node') . ' (' . $nid . ')',
        '#url' => \Drupal\Core\Url::fromUri("internal:/node/" . $nid . "/edit"),
        '#attributes' => [
          'class' => [
            'toolbar-icon',
            'toolbar-icon-edit',
          ],
        ],
        '#cache' => [
          'contexts' => [
            'url.path',
          ],
        ],
      ],
    ];
    return $items;
  }
}
