<?php

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function toolbar_edit_link_toolbar() {
  $items = [];

  $manager = \Drupal::service('plugin.manager.menu.local_task');
  $links = $manager->getLocalTasks(\Drupal::routeMatch()->getRouteName(), 0);
  if (!empty($links)) {
    $local_links = [];
    foreach ($links['tabs'] as $route => $link) {
      $local_links[$route] = $link['#link'];
    }

    foreach ($local_links as $route => $content) {
      if ($route === 'entity.node.edit_form' && isset($content['title'])) {

        $items['toolbar_edit_link'] = [
          '#type' => 'toolbar_item',
          'tab' => [
            '#type' => 'link',
            '#title' => t('Edit Page') . ' (' . $content['url']->getRouteParameters()['node'] . ')',
            '#url' => Url::fromRoute('entity.node.edit_form', $content['url']->getRouteParameters()),
            '#attributes' => [
              'title' => t('Edit Page'),
              'class' => [
                'toolbar-icon',
                'toolbar-icon-edit',
              ],
            ],
            '#cache' => [
              'contexts' => [
                'url',
              ],
            ],
          ],
        ];
      }
    }
  }

  return $items;
}
